version: '3.8'
services:
  frontend:
    build: .
    container_name: frontend-service
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["npm", "start"]
    restart: unless-stopped